// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.gob.mincyt.organizaciones.web;

import ar.gob.mincyt.organizaciones.web.EstadoBean;
import java.io.Serializable;

privileged aspect EstadoBean_Roo_Serializable {
    
    declare parents: EstadoBean implements Serializable;
    
    private static final long EstadoBean.serialVersionUID = 1L;
    
}
