// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.gob.mincyt.organizaciones.web;

import ar.gob.mincyt.organizaciones.web.IdiomaBean;
import java.io.Serializable;

privileged aspect IdiomaBean_Roo_Serializable {
    
    declare parents: IdiomaBean implements Serializable;
    
    private static final long IdiomaBean.serialVersionUID = 1L;
    
}
