// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.gob.mincyt.organizaciones.web;

import ar.gob.mincyt.organizaciones.web.NombreDeOrganizacionBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect NombreDeOrganizacionBean_Roo_Configurable {
    
    declare @type: NombreDeOrganizacionBean: @Configurable;
    
}
