// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.gob.mincyt.organizaciones.domain;

import ar.gob.mincyt.organizaciones.domain.TipoDeCategoria;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TipoDeCategoria_Roo_Configurable {
    
    declare @type: TipoDeCategoria: @Configurable;
    
}
